[package]
name = "zerostone-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "npyci"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"
zerostone = { path = ".." }
